# command line: main.py demo

config: ./config/st_gcn/kinetics-skeleton/demo_realtime.yaml
device:
- 0
fps: 30
height: 1080
ignore_weights: []
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: hand_rgbd
        strategy: spatial
    in_channels: 3
    num_class: 5
model_fps: 30
model_input_frame: 128
print_log: false
save_log: true
use_gpu: true
weights: ./models/0216(0145 0220 0306.pt
weights1: ./models/0225+avg.pt
weights2: ./models/0225+505015.pt
work_dir: ./work_dir/tmp
