weights: ./models/0226+all+noise.pt
#model_config:
#  [
# ./models/01 0222.pt,
#./models/01 0223.pt]
weights1: ./models/0225+352006.pt
weights2: ./models/0225+505015.pt
#weights: ./models/0216(0145 0220 0306.pt
#weights: ./models/0216(0145 0220 0306.pt（best
model_fps: 30
#
#feature_centers_path : ["./data/1/0225+505015.npy", "./data/111/0225+352006.npy"]
#cov_path : "./data/global_cov.npy"

model: net.st_gcn.Model
# model
model_args:
  in_channels: 3
  num_class: 5
  edge_importance_weighting: True
  graph_args:
    layout: 'hand_rgbd'
    strategy: 'spatial'
    
# training
device: [0]